sass:
    style: compressed
    sass_dir: styles/

api_version: v2
api_root: api.alpha.linode.com
login_root: login.alpha.linode.com

collections:
    guides:
        output: true
        permalink: /guides/:path/

exclude:
    - Guardfile
    - Gemfile
    - Gemfile.lock
    - config.ru
    - CNAME
    - LICENSE
    - README.md
    - vendor/
